### ISSUE TITLE
Depend on a published version of yaup

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/repo#14]
Need to publish yaup and to remove snapshot dependency

**Comment by rvansa** [comment]
I am verified for the `io.hyperfoil` groupId; not sure how I can share the permissions in Sonatype with you guys without sharing credentials.

**Comment by rvansa** [comment]
https://issues.sonatype.org/browse/OSSRH-46004

**Comment by johnaohara** [comment]
Wouldn't we need to be verified against io.hyperfoil as well?

**Comment by rvansa** [comment]
I don't know how this works, maybe you could just comment on the JIRA 'can I haz deploy too?' and I'll tell'em you're nice lad.

**Comment by johnaohara** [comment]
For others wanting push rights to Hyperfoil sonatype repo;

https://issues.sonatype.org/browse/OSSRH-54020

**Comment by rvansa** [comment]
Probably handled in 19d92ab0e2ada106a427a564d8feed86e91823e9

https://mvnrepository.com/artifact/io.hyperfoil.tools/yaup
