### ISSUE TITLE
Filter Runs by json content

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/repo#15]
query either all runs or runs for a specific test based on data content.
e.g. find all the runs that collected dstat

**Comment by rvansa** [comment]
Implemented.
@willr3 Please review & fix UI-related hacks.
@jesperpedersen The [queries](https://github.com/Hyperfoil/repo/blob/master/repo/src/main/java/io/hyperfoil/tools/repo/api/RunService.java#L64-L84) can be likely improved by materialization - please offer your suggestions.
